# Generated by Django 6.0.3 on 2026-04-22 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Price histories'},
        ),
        migrations.AlterField(
            model_name='competitor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='monitor.product'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='monitor.competitor'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='monitor.product'),
        ),
    ]
